id: deployment_frontend_backend
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: OK, so we set up everything, now we need to change the code accordingally, let's change the code to use the env variable we just set.
      - text: So let's change the frontend code and open a PR.
        delay: 1000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Checking now.
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_is_file_modified
              paramsFramework:
                node:
                  fileName: frontend/src/agent.js

            then:
              do:
              - actionId: bot_message
                params:
                  person: head-of-rd
                  messages:
                  - text: Looking good! You can merge the PR now.
              - actionId: github_pr_approve
                params:
                  person: head-of-rd
                  message: Looking good! You can merge the PR now. |
                           Oh, sweet! we also have a Netlify Deploy Preview where we can see our code before deploying it, how cool is this! 
            else:
              - actionId: github_pr_reject
                params:
                  person: devops
                  message: Are you sure you changed the right file?

        github_pr_merged:
          do:
            - actionId: finish_step
