id: deployment_frontend_configure
hints:
  - Since we're using mono repo so the base directory shuoldn't start from the root directory, but the `frontend` dir
  - To build the app we shuold use `yarn build`
  - After the build, the published website should sits in the `frontend/build` directory
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: So, as you've probably figured out by now, since we’re using a mono repo, we need to **tell Netlify how to build our frontend application**.
          - text: Luckily for you, Netlify makes it very easy for us to configure it.
            delay: 2000
          - text: You can configure it under `build settings` in the site settings.
            delay: 1500
          - text: :instruction[Once you configure it properly, trigger a new deploy], and you should see the site working. Let me know when you're done and I'll check it.
            delay: 2200
trigger:
  type: user_message
  params:
    person: head-of-rd
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
                - text: That was quick, let me see...
                  delay: 1000
          - actionId: network_find_selector
            name: card_selector
            params:
              url: https://${user.netlify.appName}.netlify.app
              selector: .card-title

          - actionId: network_find_selector
            name: no_item_selector
            params:
              url: https://${user.netlify.appName}.netlify.app
              selector: .no-items

        if:
          conditions:
            - conditionId: is_falsy
              params:
                value: ${outputs.card_selector.value}
            - conditionId: is_falsy
              params:
                value: ${outputs.no_item_selector.value}

          then:
            do:
              - actionId: bot_message
                params:
                  person: head-of-rd
                  messages:
                    - text: Umm... I tried to access [frontend app](https://${user.netlify.appName}.netlify.app) but didn’t get a valid response. Please try again. 
                    - text: Make sure to trigger a new deploy to apply your changes.
                      delay: 2200
          else:
            do:
              - actionId: bot_message
                params:
                  person: head-of-rd
                  messages:
                    - text: Sweet, we have a first version of the app working. That was quick, wasn't it?!
              - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
                - text: OK, let me know when you're done or if you need any help.
