id: netlify_open_account
hints:
- Make sure you're chosing the ObelusFamily organization when choosing the Github repo
- "App name shuold be somting like that: XXXXX1-YYYYY2-ZZZZZ3"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: We now going to deploy our frontend to Netlify
      - text: Go create a new free account in Netlify (or use your exsiting one) and create a new site by choosing "Add new site" -> "Import an existing prject"
        delay: 1000
      - text: We're going to use our exiting code so import and exiting project from Github, and choose our ${user.repoName} repo.
        delay: 1000
      - text: We're going to configure the build settings in a minute, so you can skip it for now.
        delay: 1000
      - text: Once you done, please send me your app name
        delay: 1000
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    do:
    - actionId: netlify_configure_app
      name: netlify_configure
      params:
        netlifyApp: "${userMessageText}"
    if:
      conditions:
      - conditionId: action_success
        params:
          name: netlify_configure
      then:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: Great, let's move on
              delay: 1000
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: devops
            messages:
            - text: Looks like a wrong format, are you sure?
              delay: 1000
